name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${{ github.REPOSITORY }}"
      shell: bash
    - run: echo "REPOSITORY_NAME=$(echo \"${{ github.REPOSITORY }}\")"
      shell: bash
    - run: echo "REPOSITORY_NAME=$(echo \"${{ github.REPOSITORY }}\" | awk -F / '{print $2}')"
      shell: bash
    - run: echo "REPOSITORY_NAME=$(echo \"${{ github.REPOSITORY }}\" | awk -F / '{print $2}' | sed -e \"s/:refs//\")" >> $GITHUB_ENV
      shell: bash

    - run: echo "${{ github.REPOSITORY_NAME }}"
      shell: bash
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ github.REPOSITORY_NAME }}:${{github.sha}}
